# Site Settings
lang: en


title: Simulation-based Inference
description: Simulation-based Inference is the next evolution in statistics
url: http://simulation-based-inference.org/
favicon: favicon.png
permalink: pretty
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 10
paginate_path: "/papers/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: simulation-based-inference


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  - scope:
      path: ""
    values:
      hero_height: is-small
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      show_sidebar: false

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
    
include:
  - _pages
  - _papers

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - .devcontainer/
  - .github/
  - .vscode/
  - sql/
  - scholar/
  - .dockerignore
  - .env
  - .gitignore
  - README.md
  - main.py
  - working.ipynb
  - tmp.ipynb



feed:
  disable: true