name: Daily pull

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC

jobs:
  my_cron_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./scholar/requirements.txt

    - name: Pull new articles
      env:
        SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
      run: python main.py

    - name: Check if there are any updated file
      run: if [[ "$(git diff --exit-code)" =~ 'diff' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; else echo "UPDATED=false" >> $GITHUB_ENV ;fi

    - if ${{ env.UPDATED == 'true'}}
      name: Github commit and push
      uses: Smart-Transportation/push@v1.3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'