name: Daily pull

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  
  workflow_dispatch:  # Add manually dispatch option

jobs:
  my_cron_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./scholar/requirements.txt

    - name: Pull new articles
      env:
        SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
      run: python main.py

    - name: check for changed files
      run: |
        changed_files=$(git status --porcelain | grep -E '^\?\?')
        if [ -n "$changed_files" ]; then
          echo "changed=true" >> $GITHUB_ENV
          echo "=== change detected ==="
        else
          echo "changed=false" >> $GITHUB_ENV
          echo "=== no change detected ==="
        fi

    - if: ${{ env.changed == 'true' }}
      run: |
        git config --local user.email "github-action[bot]@github.com"
        git config --local user.name "GitHub Action Bot"
        git add --all
        git commit -m "auto update publications"
        
    - if: ${{ env.changed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true